name: "Setup for Android"
description: "Install dependencies for Android"

inputs:
  use-cache:
    description: "Whether to use cache"
    required: true

runs:
  using: "composite"
  steps:
  - name: Setup JDK 11
    uses: actions/setup-java@v2
    with:
      distribution: 'zulu'
      java-version: '11'

  - uses: actions/cache@v2
    if: ${{ inputs.use-cache }}
    with:
      path: ~/.gradle/caches
      key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      restore-keys: |
        ${{ runner.os }}-gradle-

  - name: Displays the Android dependencies of the project
    run: ./gradlew androidDependencies
    shell: bash

