name: "Generate AAB"

on:
  push:
    branches:
      - release/*
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE

jobs:
  generate-aab:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: ./.github/workflows/templates/setup-android
      with:
        use-cache: false

    - name: Decode Keystore
      run: echo ${{ secrets.ENCODED_RELEASE_KEYSTORE }} | base64 --decode > ./app/release.keystore

    - name: Generate AAB
      run: ./gradlew :app:bundleProductionRelease
      env:
        RELEASE_KEYSTORE_STORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_STORE_PASSWORD }}
        RELEASE_KEYSTORE_KEY_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_KEY_PASSWORD }}

    - name: Upload AAB Artifact
      uses: actions/upload-artifact@v2
      with:
        name: aab
        path: app/build/outputs/bundle/productionRelease/app-production-release.aab
        if-no-files-found: error

